esphome:
  name: bob2
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "........"

wifi:
  ssid: "............"
  password: "............"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bob2 Fallback Hotspot"
    password: ".............."

captive_portal:


i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

sensor:

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    measurement_duration: 31
    update_interval: 5s

  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 5s  

  - platform: adc
    filters:
      - multiply: 4.2
    pin: A0
    name: "VCC Voltage" 
    update_interval: 5s

  - platform: dallas
    address: 0x7A3C01D0759D5B28
    name: "Outside Temp2"

dallas:
  - pin: GPIO13

    
deep_sleep:
  run_duration: 1min
  sleep_duration: 10min    
    
